const restaurantData = [
  {
    restaurantID: "66f5ara",
    restaurantName: "McDonalds",
    restaurantAddress: "King's Street 47905",
    distance: 0.5,
    menu: [
      "Big Mac",
      "Chicken Nuggets",
      "Fries",
      "Coke",
      "Cheeseburger",
      "McChicken",
      "Mocha Frappe",
      "Egg McMuffin",
      "Ice Cream cone",
      "Happy Meal",
    ],
    ubereatsMenuPrice: [
      5.53, 5.67, 3.07, 2.89, 3.69, 4.89, 3.29, 2.79, 1.07, 3.29,
    ],
    doordashMenuPrice: [
      5.97, 5.43, 3.81, 2.44, 3.12, 4.55, 3.16, 2.95, 1.03, 3.67,
    ],
    grubhubMenuPrice: [
      5.24, 5.51, 3.54, 2.13, 3.88, 4.15, 3.99, 2.54, 1.01, 3.24,
    ],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "images/mcd/mcd-logo.png",
    menuItemImages: [
      "/images/mcd/big mac.jpeg",
      "/images/mcd/mcnuggets.png",
      "/images/mcd/fries.jpeg",
      "/images/mcd/coke.jpeg",
      "/images/mcd/cheeseburger.jpg",
      "/images/mcd/mcchicken.jpeg",
      "/images/mcd/mochafrappe.jpeg",
      "/images/mcd/egg-mcmuffin.jpeg",
      "/images/mcd/icecream-cone.jpeg",
      "/images/mcd/happymeal.jpg",
    ],
  },
  {
    restaurantID: "13c821c",
    restaurantName: "McDonalds",
    restaurantAddress: "North Wood St 47805",
    distance: 0.8,
    menu: [
      "Big Mac",
      "Chicken Nuggets",
      "Fries",
      "Coke",
      "Cheeseburger",
      "McChicken",
      "Mocha Frappe",
      "Egg McMuff in",
      "Ice Cream cone",
      "Happy Meal",
    ],
    ubereatsMenuPrice: [
      5.11, 5.62, 3.87, 2.14, 3.35, 4.74, 3.89, 2.12, 1.12, 3.73,
    ],
    doordashMenuPrice: [
      5.85, 5.68, 3.18, 2.81, 3.38, 4.22, 3.2, 2.77, 1.11, 3.59,
    ],
    grubhubMenuPrice: [
      5.65, 5.15, 3.51, 2.88, 3.77, 4.91, 3.22, 2.75, 1.04, 3.99,
    ],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "images/mcd/mcd-logo.png",
    menuItemImages: [
      "/images/mcd/big mac.jpeg",
      "/images/mcd/mcnuggets.png",
      "/images/mcd/fries.jpeg",
      "/images/mcd/coke.jpeg",
      "/images/mcd/cheeseburger.jpg",
      "/images/mcd/mcchicken.jpeg",
      "/images/mcd/mochafrappe.jpeg",
      "/images/mcd/egg-mcmuffin.jpeg",
      "/images/mcd/icecream-cone.jpeg",
      "/images/mcd/happymeal.jpg",
    ],
  },
  {
    restaurantID: "21e7b6f",
    restaurantName: "McDonalds",
    restaurantAddress: "Elm Drive 48085",
    distance: 1.2,
    menu: [
      "Big Mac",
      "Chicken Nuggets",
      "Fries",
      "Coke",
      "Cheeseburger",
      "McChicken",
      "Mocha Frappe",
      "Egg McMuffin",
      "Ice Cream cone",
      "Happy Meal",
    ],
    ubereatsMenuPrice: [
      5.45, 5.55, 3.22, 2.99, 3.79, 4.79, 3.33, 2.67, 1.15, 3.25,
    ],
    doordashMenuPrice: [
      5.99, 5.42, 3.12, 2.57, 3.5, 4.25, 3.14, 2.83, 1.11, 3.75,
    ],
    grubhubMenuPrice: [5.3, 5.41, 3.44, 2.22, 3.8, 4.3, 3.66, 2.61, 1.08, 3.48],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "images/mcd/mcd-logo.png",
    menuItemImages: [
      "/images/mcd/big mac.jpeg",
      "/images/mcd/mcnuggets.png",
      "/images/mcd/fries.jpeg",
      "/images/mcd/coke.jpeg",
      "/images/mcd/cheeseburger.jpg",
      "/images/mcd/mcchicken.jpeg",
      "/images/mcd/mochafrappe.jpeg",
      "/images/mcd/egg-mcmuffin.jpeg",
      "/images/mcd/icecream-cone.jpeg",
      "/images/mcd/happymeal.jpg",
    ],
  },
  {
    restaurantID: "89d3c1b",
    restaurantName: "McDonalds",
    restaurantAddress: "Main Street 48212",
    distance: 2.5,
    menu: [
      "Big Mac",
      "Chicken Nuggets",
      "Fries",
      "Coke",
      "Cheeseburger",
      "McChicken",
      "Mocha Frappe",
      "Egg McMuffin",
      "Ice Cream cone",
      "Happy Meal",
    ],
    ubereatsMenuPrice: [
      5.35, 5.75, 3.67, 2.74, 3.43, 4.67, 3.42, 2.84, 1.22, 3.41,
    ],
    doordashMenuPrice: [
      5.85, 5.35, 3.25, 2.41, 3.11, 4.45, 3.12, 2.79, 1.05, 3.5,
    ],
    grubhubMenuPrice: [
      5.28, 5.33, 3.49, 2.33, 3.69, 4.11, 3.75, 2.56, 1.03, 3.3,
    ],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "images/mcd/mcd-logo.png",
    menuItemImages: [
      "/images/mcd/big mac.jpeg",
      "/images/mcd/mcnuggets.png",
      "/images/mcd/fries.jpeg",
      "/images/mcd/coke.jpeg",
      "/images/mcd/cheeseburger.jpg",
      "/images/mcd/mcchicken.jpeg",
      "/images/mcd/mochafrappe.jpeg",
      "/images/mcd/egg-mcmuffin.jpeg",
      "/images/mcd/icecream-cone.jpeg",
      "/images/mcd/happymeal.jpg",
    ],
  },
  {
    restaurantID: "35ab42f",
    restaurantName: "KFC",
    restaurantAddress: "Main Avenue 40205",
    distance: 1.0,
    menu: [
      "Fried Chicken Bucket",
      "Chicken Sandwich Deluxe",
      "Popcorn Chicken",
      "Chicken Tenders",
      "Mashed Potatoes",
      "Coleslaw",
      "Mac and Cheese",
      "Biscuit",
      "Chocolate Chip Cookie",
      "Fountain Drink",
    ],
    ubereatsMenuPrice: [
      21.5, 6.75, 4.25, 7.4, 2.99, 2.25, 3.49, 1.69, 1.5, 2.29,
    ],
    doordashMenuPrice: [
      22.05, 6.5, 4.4, 7.25, 2.79, 2.4, 3.35, 1.55, 1.45, 2.1,
    ],
    grubhubMenuPrice: [
      20.99, 6.9, 4.35, 7.55, 2.89, 2.19, 3.59, 1.6, 1.35, 2.45,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/kfc/kfc-logo.png",
    menuItemImages: [
      "/images/kfc/fried_chicken_bucket.jpg",
      "/images/kfc/chicken_sandwich.jpg",
      "/images/kfc/popcorn_chicken.jpg",
      "/images/kfc/chicken_tenders.jpg",
      "/images/kfc/mashed_potatoes.jpg",
      "/images/kfc/coleslaw.jpg",
      "/images/kfc/mac.jpg",
      "/images/kfc/biscuit.jpg",
      "/images/kfc/cookie.jpg",
      "/images/kfc/drink.jpg",
    ],
  },
  {
    restaurantID: "54cd31e",
    restaurantName: "KFC",
    restaurantAddress: "Broadway St 40321",
    distance: 1.6,
    menu: [
      "Fried Chicken Bucket",
      "Chicken Sandwich Deluxe",
      "Popcorn Chicken",
      "Chicken Tenders",
      "Mashed Potatoes",
      "Coleslaw",
      "Mac and Cheese",
      "Biscuit",
      "Chocolate Chip Cookie",
      "Fountain Drink",
    ], //     ubereatsMenuPrice: [21.95, 6.55, 4.45, 7.20, 3.05, 2.15, 3.29, 1.59, 1.40, 2.35],
    doordashMenuPrice: [22.1, 6.6, 4.5, 7.3, 2.95, 2.35, 3.15, 1.5, 1.55, 2.2],
    grubhubMenuPrice: [21.3, 6.8, 4.55, 7.45, 3.1, 2.2, 3.45, 1.62, 1.55, 2.3],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/kfc/kfc-logo.png",
    menuItemImages: [
      "/images/kfc/fried_chicken_bucket.jpg",
      "/images/kfc/chicken_sandwich.jpg",
      "/images/kfc/popcorn_chicken.jpg",
      "/images/kfc/chicken_tenders.jpg",
      "/images/kfc/mashed_potatoes.jpg",
      "/images/kfc/coleslaw.jpg",
      "/images/kfc/mac.jpg",
      "/images/kfc/biscuit.jpg",
      "/images/kfc/cookie.jpg",
      "/images/kfc/drink.jpg",
    ],
  },
  {
    restaurantID: "23df67b",
    restaurantName: "KFC",
    restaurantAddress: "Lakeshore Rd 40011",
    distance: 2.2,
    menu: [
      "Fried Chicken Bucket",
      "Chicken Sandwich Deluxe",
      "Popcorn Chicken",
      "Chicken Tenders",
      "Mashed Potatoes",
      "Coleslaw",
      "Mac and Cheese",
      "Biscuit",
      "Chocolate Chip Cookie",
      "Fountain Drink",
    ], //     ubereatsMenuPrice: [22.25, 6.65, 4.30, 7.35, 2.99, 2.29, 3.49, 1.65, 1.45, 2.30],
    doordashMenuPrice: [
      21.85, 6.4, 4.25, 7.15, 2.75, 2.2, 3.25, 1.5, 1.5, 2.15,
    ],
    grubhubMenuPrice: [
      21.7, 6.75, 4.55, 7.5, 2.89, 2.15, 3.55, 1.69, 1.6, 2.35,
    ],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/kfc/kfc-logo.png",
    menuItemImages: [
      "/images/kfc/fried_chicken_bucket.jpg",
      "/images/kfc/chicken_sandwich.jpg",
      "/images/kfc/popcorn_chicken.jpg",
      "/images/kfc/chicken_tenders.jpg",
      "/images/kfc/mashed_potatoes.jpg",
      "/images/kfc/coleslaw.jpg",
      "/images/kfc/mac.jpg",
      "/images/kfc/biscuit.jpg",
      "/images/kfc/cookie.jpg",
      "/images/kfc/drink.jpg",
    ],
  },
  {
    restaurantID: "91ae82d",
    restaurantName: "KFC",
    restaurantAddress: "Willow St 40165",
    distance: 3.0,
    menu: [
      "Fried Chicken Bucket",
      "Chicken Sandwich Deluxe",
      "Popcorn Chicken",
      "Chicken Tenders",
      "Mashed Potatoes",
      "Coleslaw",
      "Mac and Cheese",
      "Biscuit",
      "Chocolate Chip Cookie",
      "Fountain Drink",
    ],
    ubereatsMenuPrice: [21.65, 6.50, 4.35, 7.50, 3.05, 2.35, 3.65, 1.55, 1.55, 2.20],
    doordashMenuPrice: [22.3, 6.55, 4.25, 7.2, 2.95, 2.4, 3.45, 1.5, 1.6, 2.1],
    grubhubMenuPrice: [
      21.85, 6.7, 4.45, 7.35, 2.99, 2.25, 3.6, 1.65, 1.5, 2.25,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/kfc/kfc-logo.png",
    menuItemImages: [
      "/images/kfc/fried_chicken_bucket.jpg",
      "/images/kfc/chicken_sandwich.jpg",
      "/images/kfc/popcorn_chicken.jpg",
      "/images/kfc/chicken_tenders.jpg",
      "/images/kfc/mashed_potatoes.jpg",
      "/images/kfc/coleslaw.jpg",
      "/images/kfc/mac.jpg",
      "/images/kfc/biscuit.jpg",
      "/images/kfc/cookie.jpg",
      "/images/kfc/drink.jpg",
    ],
  },
  {
    restaurantID: "12ab34c",
    restaurantName: "Burger King",
    restaurantAddress: "Oak Street 30521",
    distance: 1.5,
    menu: [
      "Whopper",
      "Chicken Fries",
      "Impossible Whopper",
      "Chicken Sandwich",
      "French Fries",
      "Onion Rings",
      "Mozzarella Sticks",
      "Chocolate Shake",
      "Soft Drink",
      "King Jr.Meal",
    ],
    ubereatsMenuPrice: [
      6.49, 4.29, 6.99, 5.39, 2.99, 2.79, 3.29, 3.99, 2.29, 4.99,
    ],
    doordashMenuPrice: [
      6.79, 4.1, 6.79, 5.59, 2.89, 2.99, 3.39, 3.89, 2.19, 5.09,
    ],
    grubhubMenuPrice: [
      6.29, 4.45, 7.09, 5.19, 3.09, 2.69, 3.19, 3.79, 2.35, 4.79,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    restaurantImage: "/images/burger_king/bk-logo.png",
    menuItemImages: [
      "/images/burger_king/whopper.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/impossible.jpg",
      "/images/burger_king/chicken_sandwich.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/onion_rings.jpg",
      "/images/burger_king/mozzarella_sticks.jpg",
      "/images/burger_king/shake.jpg",
      "/images/burger_king/drink.jpg",
      "/images/burger_king/jr_meal.jpg",
    ],
  },
  {
    restaurantID: "56cd78e",
    restaurantName: "Burger King",
    restaurantAddress: "Pine Avenue 30612",
    distance: 2.3,
    menu: [
      "Whopper",
      "Chicken Fries",
      "Impossible Whopper",
      "Chicken Sandwich",
      "French Fries",
      "Onion Rings",
      "Mozzarella Sticks",
      "Chocolate Shake",
      "Soft Drink",
      "King Jr.Meal",
    ],
    ubereatsMenuPrice: [
      6.55, 4.19, 7.1, 5.49, 3.05, 2.69, 3.39, 3.89, 2.25, 5.19,
    ],
    doordashMenuPrice: [
      6.99, 4.25, 6.99, 5.69, 2.95, 2.89, 3.25, 3.79, 2.15, 4.99,
    ],
    grubhubMenuPrice: [6.39, 4.5, 7.2, 5.25, 3.19, 2.79, 3.1, 3.99, 2.45, 5.09],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    restaurantImage: "/images/burger_king/bk-logo.png",
    menuItemImages: [
      "/images/burger_king/whopper.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/impossible.jpg",
      "/images/burger_king/chicken_sandwich.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/onion_rings.jpg",
      "/images/burger_king/mozzarella_sticks.jpg",
      "/images/burger_king/shake.jpg",
      "/images/burger_king/drink.jpg",
      "/images/burger_king/jr_meal.jpg",
    ],
  },
  {
    restaurantID: "34ab90d",
    restaurantName: "Burger King",
    restaurantAddress: "Lakeview Rd 30911",
    distance: 3.0,
    menu: [
      "Whopper",
      "Chicken Fries",
      "Impossible Whopper",
      "Chicken Sandwich",
      "French Fries",
      "Onion Rings",
      "Mozzarella Sticks",
      "Chocolate Shake",
      "Soft Drink",
      "King Jr.Meal",
    ],
    ubereatsMenuPrice: [
      6.39, 4.15, 7.05, 5.35, 3.19, 2.89, 3.19, 3.69, 2.29, 4.89,
    ],
    doordashMenuPrice: [
      6.59, 4.35, 6.95, 5.65, 3.05, 2.79, 3.25, 3.79, 2.39, 5.05,
    ],
    grubhubMenuPrice: [
      6.49, 4.55, 7.15, 5.45, 3.09, 2.95, 3.35, 3.99, 2.45, 4.95,
    ],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    restaurantImage: "/images/burger_king/bk-logo.png",
    menuItemImages: [
      "/images/burger_king/whopper.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/impossible.jpg",
      "/images/burger_king/chicken_sandwich.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/onion_rings.jpg",
      "/images/burger_king/mozzarella_sticks.jpg",
      "/images/burger_king/shake.jpg",
      "/images/burger_king/drink.jpg",
      "/images/burger_king/jr_meal.jpg",
    ],
  },
  {
    restaurantID: "78ef34g",
    restaurantName: "Burger King",
    restaurantAddress: "Elm Street 31001",
    distance: 1.8,
    menu: [
      "Whopper",
      "Chicken Fries",
      "Impossible Whopper",
      "Chicken Sandwich",
      "French Fries",
      "Onion Rings",
      "Mozzarella Sticks",
      "Chocolate Shake",
      "Soft Drink",
      "King Jr.Meal",
    ],
    ubereatsMenuPrice: [
      6.69, 4.2, 6.85, 5.29, 3.09, 2.79, 3.09, 3.79, 2.19, 5.09,
    ],
    doordashMenuPrice: [
      6.89, 4.39, 7.05, 5.59, 2.95, 2.95, 3.15, 3.89, 2.25, 5.29,
    ],
    grubhubMenuPrice: [
      6.55, 4.49, 7.0, 5.39, 3.29, 2.85, 3.35, 3.85, 2.35, 5.19,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    restaurantImage: "/images/burger_king/bk-logo.png",
    menuItemImages: [
      "/images/burger_king/whopper.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/impossible.jpg",
      "/images/burger_king/chicken_sandwich.jpg",
      "/images/burger_king/chicken_fries.jpg",
      "/images/burger_king/onion_rings.jpg",
      "/images/burger_king/mozzarella_sticks.jpg",
      "/images/burger_king/shake.jpg",
      "/images/burger_king/drink.jpg",
      "/images/burger_king/jr_meal.jpg",
    ],
  },
  {
    restaurantID: "17cd32x",
    restaurantName: "Chipotle",
    restaurantAddress: "Park Avenue 70512",
    distance: 0.9,
    menu: [
      "Burrito",
      "Burrito Bowl",
      "Tacos",
      "Salad",
      "Chips & Guacamole",
      "Quesadilla",
      "Sofritas Bowl",
      "Steak Bowl",
      "Barbacoa Burrito",
      "Chicken Burrito",
    ],
    ubereatsMenuPrice: [8.25, 8.15, 7.85, 7.5, 4.25, 8.95, 8.0, 9.45, 9.1, 8.5],
    doordashMenuPrice: [8.5, 8.25, 7.75, 7.35, 4.5, 9.1, 8.25, 9.65, 9.3, 8.4],
    grubhubMenuPrice: [8.4, 8.2, 7.95, 7.6, 4.35, 9.0, 8.15, 9.55, 9.2, 8.6],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Mexican",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chipotle/chipotle-logo.png",
    menuItemImages: [
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/tacos.jpg",
      "/images/chipotle/salad.jpg",
      "/images/chipotle/chips_guac.jpg",
      "/images/chipotle/quesadilla.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/burrito.jpg",
    ],
  },

  ,
  {
    restaurantID: "23ef67y",
    restaurantName: "Chipotle",
    restaurantAddress: "Cedar Street 70612",
    distance: 1.2,
    menu: [
      "Burrito",
      "Burrito Bowl",
      "Tacos",
      "Salad",
      "Chips & Guacamole",
      "Quesadilla",
      "Sofritas Bowl",
      "Steak Bowl",
      "Barbacoa Burrito",
      "Chicken Burrito",
    ],
    ubereatsMenuPrice: [8.45, 8.3, 7.75, 7.4, 4.35, 9.05, 8.1, 9.5, 9.15, 8.35],
    doordashMenuPrice: [8.6, 8.4, 7.65, 7.5, 4.55, 9.15, 8.2, 9.75, 9.35, 8.55],
    grubhubMenuPrice: [8.3, 8.2, 7.8, 7.45, 4.4, 9.0, 8.0, 9.55, 9.1, 8.45],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chipotle/chipotle-logo.png",
    menuItemImages: [
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/tacos.jpg",
      "/images/chipotle/salad.jpg",
      "/images/chipotle/chips_guac.jpg",
      "/images/chipotle/quesadilla.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/burrito.jpg",
    ],
  },
  {
    restaurantID: "37fg89z",
    restaurantName: "Chipotle",
    restaurantAddress: "River Road 70721",
    distance: 2.0,
    menu: [
      "Burrito",
      "Burrito Bowl",
      "Tacos",
      "Salad",
      "Chips & Guacamole",
      "Quesadilla",
      "Sofritas Bowl",
      "Steak Bowl",
      "Barbacoa Burrito",
      "Chicken Burrito",
    ],
    ubereatsMenuPrice: [8.3, 8.1, 7.95, 7.55, 4.4, 9.1, 8.25, 9.4, 9.05, 8.6],
    doordashMenuPrice: [8.65, 8.45, 7.8, 7.6, 4.6, 9.25, 8.3, 9.65, 9.45, 8.7],
    grubhubMenuPrice: [8.25, 8.0, 7.85, 7.5, 4.3, 9.05, 8.1, 9.5, 9.2, 8.5],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Mexican",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chipotle/chipotle-logo.png",
    menuItemImages: [
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/tacos.jpg",
      "/images/chipotle/salad.jpg",
      "/images/chipotle/chips_guac.jpg",
      "/images/chipotle/quesadilla.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/burrito.jpg",
    ],
  },
  {
    restaurantID: "45hi12w",
    restaurantName: "Chipotle",
    restaurantAddress: "Maple Avenue 70812",
    distance: 1.5,
    menu: [
      "Burrito",
      "Burrito Bowl",
      "Tacos",
      "Salad",
      "Chips & Guacamole",
      "Quesadilla",
      "Sofritas Bowl",
      "Steak Bowl",
      "Barbacoa Burrito",
      "Chicken Burrito",
    ],
    ubereatsMenuPrice: [
      8.55, 8.35, 7.85, 7.65, 4.45, 9.2, 8.35, 9.55, 9.25, 8.5,
    ],
    doordashMenuPrice: [
      8.7, 8.45, 7.95, 7.7, 4.55, 9.35, 8.45, 9.6, 9.35, 8.75,
    ],
    grubhubMenuPrice: [8.35, 8.1, 7.75, 7.6, 4.5, 9.1, 8.2, 9.5, 9.15, 8.6],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chipotle/chipotle-logo.png",
    menuItemImages: [
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/tacos.jpg",
      "/images/chipotle/salad.jpg",
      "/images/chipotle/chips_guac.jpg",
      "/images/chipotle/quesadilla.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/bowl.jpg",
      "/images/chipotle/burrito.jpg",
      "/images/chipotle/burrito.jpg",
    ],
  },
  {
    restaurantID: "99bc12x",
    restaurantName: "Applebee's",
    restaurantAddress: "Sunset Blvd 30125",
    distance: 1.2,
    menu: [
      "Bourbon Street Chicken & Shrimp",
      "Classic Bacon Cheeseburger",
      "Chicken Tenders Platter",
      "Fiesta Lime Chicken",
      "Mozzarella Sticks",
      "Four Cheese Mac & Cheese with Honey Pepper Chicken Tenders",
      "Oriental Chicken Salad",
      "Double - Glazed Baby Back Ribs",
      "Triple Chocolate Meltdown",
      "Classic Fries",
    ],
    ubereatsMenuPrice: [
      16.99, 12.5, 11.25, 13.75, 7.49, 15.5, 12.99, 18.99, 7.25, 3.99,
    ],
    doordashMenuPrice: [
      17.25, 12.75, 11.5, 13.5, 7.25, 15.75, 13.25, 19.25, 7.0, 4.25,
    ],
    grubhubMenuPrice: [
      16.5, 12.65, 11.35, 13.85, 7.35, 15.6, 12.85, 18.85, 7.1, 4.0,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/applebees/applebees-logo.png",
    menuItemImages: [
      "/images/applebees/bourbon_street_chicken_shrimp.jpg",
      "/images/applebees/bacon_cheeseburger.jpg",
      "/images/applebees/chicken_tenders_platter.jpg",
      "/images/applebees/fiesta_lime_chicken.jpg",
      "/images/applebees/mozzarella_sticks.jpg",
      "/images/applebees/mac_and_honey_pepper_chicken_tenders.jpg",
      "/images/applebees/oriental_chicken_salad.jpg",
      "/images/applebees/ribs.jpg",
      "/images/applebees/chocolate_meltdown.jpg",
      "/images/applebees/fries.jpg",
    ],
  },
  {
    restaurantID: "12de45z",
    restaurantName: "Applebee's",
    restaurantAddress: "Lakeside Rd 30589",
    distance: 2.5,
    menu: [
      "Bourbon Street Chicken & Shrimp",
      "Classic Bacon Cheeseburger",
      "Chicken Tenders Platter",
      "Fiesta Lime Chicken",
      "Mozzarella Sticks",
      "Four Cheese Mac & Cheese with Honey Pepper Chicken Tenders",
      "Oriental Chicken Salad",
      "Double - Glazed Baby Back Ribs",
      "Triple Chocolate Meltdown",
      "Classic Fries",
    ],
    ubereatsMenuPrice: [
      17.15, 12.45, 11.55, 13.55, 7.29, 15.85, 13.05, 19.1, 7.15, 4.1,
    ],
    doordashMenuPrice: [
      17.35, 12.65, 11.7, 13.85, 7.4, 15.95, 13.2, 19.45, 7.25, 4.25,
    ],
    grubhubMenuPrice: [
      16.95, 12.4, 11.4, 13.4, 7.1, 15.7, 12.9, 19.05, 7.0, 4.0,
    ],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/applebees/applebees-logo.png",
    menuItemImages: [
      "/images/applebees/bourbon_street_chicken_shrimp.jpg",
      "/images/applebees/bacon_cheeseburger.jpg",
      "/images/applebees/chicken_tenders_platter.jpg",
      "/images/applebees/fiesta_lime_chicken.jpg",
      "/images/applebees/mozzarella_sticks.jpg",
      "/images/applebees/mac_and_honey_pepper_chicken_tenders.jpg",
      "/images/applebees/oriental_chicken_salad.jpg",
      "/images/applebees/ribs.jpg",
      "/images/applebees/chocolate_meltdown.jpg",
      "/images/applebees/fries.jpg",
    ],
  },
  {
    restaurantID: "45ef67y",
    restaurantName: "Applebee's",
    restaurantAddress: "Mountain View Ave 30878",
    distance: 3.0,
    menu: [
      "Bourbon Street Chicken & Shrimp",
      "Classic Bacon Cheeseburger",
      "Chicken Tenders Platter",
      "Fiesta Lime Chicken",
      "Mozzarella Sticks",
      "Four Cheese Mac & Cheese with Honey Pepper Chicken Tenders",
      "Oriental Chicken Salad",
      "Double - Glazed Baby Back Ribs",
      "Triple Chocolate Meltdown",
      "Classic Fries",
    ],
    ubereatsMenuPrice: [
      17.05, 12.55, 11.4, 13.6, 7.35, 15.6, 12.8, 18.9, 7.05, 4.15,
    ],
    doordashMenuPrice: [
      17.45, 12.85, 11.7, 13.95, 7.45, 16.1, 13.1, 19.35, 7.15, 4.35,
    ],
    grubhubMenuPrice: [
      16.75, 12.65, 11.45, 13.65, 7.25, 15.75, 12.95, 19.0, 7.1, 4.05,
    ],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/applebees/applebees-logo.png",
    menuItemImages: [
      "/images/applebees/bourbon_street_chicken_shrimp.jpg",
      "/images/applebees/bacon_cheeseburger.jpg",
      "/images/applebees/chicken_tenders_platter.jpg",
      "/images/applebees/fiesta_lime_chicken.jpg",
      "/images/applebees/mozzarella_sticks.jpg",
      "/images/applebees/mac_and_honey_pepper_chicken_tenders.jpg",
      "/images/applebees/oriental_chicken_salad.jpg",
      "/images/applebees/ribs.jpg",
      "/images/applebees/chocolate_meltdown.jpg",
      "/images/applebees/fries.jpg",
    ],
  },

  {
    restaurantID: "67gh89v",
    restaurantName: "Applebee's",
    restaurantAddress: "Ocean Drive 30999",
    distance: 1.8,
    menu: [
      "Bourbon Street Chicken & Shrimp",
      "Classic Bacon Cheeseburger",
      "Chicken Tenders Platter",
      "Fiesta Lime Chicken",
      "Mozzarella Sticks",
      "Four Cheese Mac & Cheese with Honey Pepper Chicken Tenders",
      "Oriental Chicken Salad",
      "Double - Glazed Baby Back Ribs",
      "Triple Chocolate Meltdown",
      "Classic Fries",
    ],
    ubereatsMenuPrice: [
      16.85, 12.3, 11.65, 13.35, 7.3, 15.9, 13.0, 18.95, 7.25, 3.85,
    ],
    doordashMenuPrice: [
      17.2, 12.55, 11.55, 13.6, 7.5, 16.05, 13.15, 19.25, 7.3, 4.1,
    ],
    grubhubMenuPrice: [
      16.95, 12.4, 11.45, 13.45, 7.15, 15.85, 12.9, 19.05, 7.05, 3.9,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/applebees/applebees-logo.png",
    menuItemImages: [
      "/images/applebees/bourbon_street_chicken_shrimp.jpg",
      "/images/applebees/bacon_cheeseburger.jpg",
      "/images/applebees/chicken_tenders_platter.jpg",
      "/images/applebees/fiesta_lime_chicken.jpg",
      "/images/applebees/mozzarella_sticks.jpg",
      "/images/applebees/mac_and_honey_pepper_chicken_tenders.jpg",
      "/images/applebees/oriental_chicken_salad.jpg",
      "/images/applebees/ribs.jpg",
      "/images/applebees/chocolate_meltdown.jpg",
      "/images/applebees/fries.jpg",
    ],
  },
  {
    restaurantID: "87ab12x",
    restaurantName: "Bistro Bella",
    restaurantAddress: "456 Grove Street, 10121",
    distance: 2.0,
    menu: [
      "Grilled Salmon",
      "Pasta Primavera",
      "Beef Wellington",
      "Caesar Salad",
      "Bruschetta",
      "Clam Chowder",
      "Tiramisu",
      "Chocolate Fondant",
      "French Fries",
      "Espresso",
    ],
    ubereatsMenuPrice: [
      22.95, 16.5, 28.0, 11.25, 9.75, 7.95, 6.5, 8.25, 5.5, 3.0,
    ],
    doordashMenuPrice: [
      23.5, 16.75, 27.75, 11.5, 9.5, 7.85, 6.75, 8.5, 5.25, 3.1,
    ],
    grubhubMenuPrice: [22.7, 16.2, 28.3, 11.6, 9.8, 7.99, 6.45, 8.1, 5.6, 3.15],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Italian",
    operatingHours: ["Breakfast", "Brunch", "Lunch"],
    restaurantImage: "/images/bistro_bella/bistro-bella-vita-logo.jpg",
    menuItemImages: [
      "/images/bistro_bella/grilled_salmon.png",
      "/images/bistro_bella/pasta_primavera.jpg",
      "/images/bistro_bella/beef_wellington.webp",
      "/images/bistro_bella/caesar_salad.jpg",
      "/images/bistro_bella/bruschetta.jpg",
      "/images/bistro_bella/clam_chowder.jpg",
      "/images/bistro_bella/tiramisu.jpg",
      "/images/bistro_bella/chocolate_fondant.jpg",
      "/images/bistro_bella/fries.png",
      "/images/bistro_bella/espresso.jpg",
    ],
  },

  {
    restaurantID: "91de34v",
    restaurantName: "The Vegan Haven",
    restaurantAddress: "325 Riverside Blvd, 10221",
    distance: 1.2,
    menu: [
      "Vegan Burger",
      "Quinoa Salad",
      "Vegan Nachos",
      "Tofu Stir - Fry",
      "Vegan Pizza",
      "Sweet Potato Fries",
      "Lentil Soup",
      "Avocado Toast",
      "Vegan Brownie",
      "Iced Matcha Latte",
    ],
    ubereatsMenuPrice: [
      12.95, 10.5, 9.75, 13.25, 14.0, 5.95, 7.5, 8.95, 4.25, 6.75,
    ],
    doordashMenuPrice: [
      13.1, 10.6, 9.5, 13.5, 14.25, 6.1, 7.75, 9.25, 4.5, 6.95,
    ],
    grubhubMenuPrice: [
      12.85, 10.45, 9.8, 13.1, 14.1, 5.9, 7.35, 8.8, 4.35, 6.85,
    ],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/the_vegan_haven/vegan_haven_logo.png",
    menuItemImages: [
      "/images/the_vegan_haven/vegan_burger.webp",
      "/images/the_vegan_haven/quinoa-salad.jpg",
      "/images/the_vegan_haven/vegan_nachos.webp",
      "/images/the_vegan_haven/tofu_stirfry.jpg",
      "/images/the_vegan_haven/vegan-pizza.jpg",
      "/images/the_vegan_haven/baked-sweet-potato-fries-12.jpg",
      "/images/the_vegan_haven/lentil soup.jpg",
      "/images/the_vegan_haven/avocado-toast-hero-cropped.jpg",
      "/images/the_vegan_haven/vegan brownie.jpg",
      "/images/the_vegan_haven/iced-matcha-latte-hero.webp",
    ],
  },

  {
    restaurantID: "54cd67b",
    restaurantName: "The Rustic Table",
    restaurantAddress: "78 Main Street, 10331",
    distance: 0.8,
    menu: [
      "BBQ Pulled Pork Sandwich",
      "Roast Chicken",
      "Beef Brisket",
      "Cornbread",
      "House Salad",
      "Fried Green Tomatoes",
      "Mac and Cheese",
      "Apple Pie",
      "Sweet Tea",
      "Lemonade",
    ],
    ubereatsMenuPrice: [
      10.95, 17.5, 18.95, 4.5, 6.95, 7.25, 8.5, 5.75, 2.95, 3.5,
    ],
    doordashMenuPrice: [
      11.25, 17.35, 19.1, 4.75, 6.8, 7.5, 8.6, 5.65, 2.9, 3.75,
    ],
    grubhubMenuPrice: [
      10.85, 17.2, 18.85, 4.4, 6.7, 7.35, 8.7, 5.8, 3.05, 3.65,
    ],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Dinner"],
    restaurantImage: "/images/the_rustic_table/rustic_table_logo.jpg",
    menuItemImages: [
      "/images/the_rustic_table/bbq_pulled_pork.jpg",
      "/images/the_rustic_table/roast-chicken.avif",
      "/images/the_rustic_table/beef-brisket-20.jpg",
      "/images/the_rustic_table/cornbread.jpg",
      "/images/the_rustic_table/house_salad.jpg",
      "/images/the_rustic_table/Fried-Green-Tomatoes.jpeg",
      "/images/the_rustic_table/mac_cheese.jpg",
      "/images/the_rustic_table/apple-pie.jpg",
      "/images/the_rustic_table/sweet-tea.webp",
      "/images/the_rustic_table/lemonade.jpg",
    ],
  },
  {
    restaurantID: "54gh78b",
    restaurantName: "The Pasta House",
    restaurantAddress: "122 Maple Street, 30456",
    distance: 0.9,
    menu: [
      "Spaghetti Bolognese",
      "Fettuccine Alfredo",
      "Lasagna",
      "Penne Arrabbiata",
      "Garlic Bread",
      "Caesar Salad",
      "Minestrone Soup",
      "Tiramisu",
      "Cannoli",
      "Espresso",
    ],
    ubereatsMenuPrice: [
      13.5, 12.25, 14.0, 11.75, 3.5, 6.95, 5.5, 7.25, 5.95, 3.25,
    ],
    doordashMenuPrice: [
      13.75, 12.5, 14.25, 11.95, 3.25, 7.1, 5.65, 7.5, 6.05, 3.35,
    ],
    grubhubMenuPrice: [13.3, 12.15, 13.85, 11.6, 3.4, 6.8, 5.4, 7.15, 5.8, 3.2],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Italian",
    operatingHours: ["Breakfast", "Brunch", "Lunch", "Dinner"],
    restaurantImage: "/images/the_pasta_house/the-pasta-house-logo.jpg",
    menuItemImages: [
      "/images/the_pasta_house/spaghetti-bolog.avif",
      "/images/the_pasta_house/fettuccine.jpg",
      "/images/the_pasta_house/lasagna.jpg",
      "/images/the_pasta_house/penne-arrabbiata-with-chickpeas2.jpg",
      "/images/the_pasta_house/19192garlic_bread.avif",
      "/images/the_pasta_house/caesarsalad.jpg",
      "/images/the_pasta_house/minestrone.webp",
      "/images/the_pasta_house/tiramisu.webp",
      "/images/the_pasta_house/cannoli.jpg",
      "/images/the_pasta_house/espresso-pastahouse.webp",
    ],
  },
  {
    restaurantID: "39kl91q",
    restaurantName: "Taco Fiesta",
    restaurantAddress: "50 Fiesta Plaza, 40123",
    distance: 1.5,
    menu: [
      "Taco",
      "Burrito",
      "Quesadilla",
      "Nachos",
      "Guacamole",
      "Churros",
      "Fajitas",
      "Tortilla Soup",
      "Mexican Rice",
      "Horchata",
    ],
    ubereatsMenuPrice: [
      3.95, 8.25, 7.75, 6.5, 4.95, 3.25, 11.5, 5.95, 3.5, 2.75,
    ],
    doordashMenuPrice: [4.1, 8.5, 8.0, 6.75, 5.1, 3.45, 11.75, 6.1, 3.65, 2.85],
    grubhubMenuPrice: [3.85, 8.15, 7.5, 6.4, 4.85, 3.3, 11.4, 5.85, 3.45, 2.7],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["Breakfast", "Brunch", "Dinner"],
    restaurantImage: "/images/taco_fiesta/tacofiesta_logo.avif",
    menuItemImages: [
      "/images/taco_fiesta/taco.webp",
      "/images/taco_fiesta/burrito.webp",
      "/images/taco_fiesta/Quesadilla.jpg",
      "/images/taco_fiesta/nachos.webp",
      "/images/taco_fiesta/guac.webp",
      "/images/taco_fiesta/churros.jpg",
      "/images/taco_fiesta/fajitas.webp",
      "/images/taco_fiesta/tortilla-soup.jpg",
      "/images/taco_fiesta/mexican_rice.jpg",
      "/images/taco_fiesta/horchata-6.jpg",
    ],
  },

  //NEW DATA
  {
    restaurantID: "a1b2c3d",
    restaurantName: "Wendy's",
    restaurantAddress: "123 Maple Street, 12345",
    distance: 0.7,
    menu: [
      "Dave's Single",
      "Spicy Chicken Sandwich",
      "Baconator",
      "Nuggets",
      "Frosty",
      "Fries",
      "Chili",
      "Baked Potato",
      "Garden Salad",
      "Homestyle Chicken Sandwich"
    ],
    ubereatsMenuPrice: [5.49, 5.99, 6.99, 4.49, 1.99, 2.19, 2.99, 3.49, 4.99, 5.59],
    doordashMenuPrice: [5.69, 5.89, 7.19, 4.39, 1.89, 2.29, 2.89, 3.39, 4.89, 5.49],
    grubhubMenuPrice: [5.59, 6.09, 7.09, 4.59, 1.79, 2.09, 2.79, 3.29, 4.79, 5.69],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/wendys/wendys-logo.png",
    menuItemImages: [
      "/images/wendys/daves_single.jpg",
      "/images/wendys/spicy_chicken_sandwich.jpg",
      "/images/wendys/baconator.jpg",
      "/images/wendys/nuggets.jpg",
      "/images/wendys/frosty.jpg",
      "/images/wendys/fries.jpg",
      "/images/wendys/chili.jpg",
      "/images/wendys/baked_potato.jpg",
      "/images/wendys/garden_salad.jpg",
      "/images/wendys/homestyle_chicken_sandwich.jpg"
    ]
  },
  {
    restaurantID: "e4f5g6h",
    restaurantName: "Wendy's",
    restaurantAddress: "456 Oak Avenue, 12346",
    distance: 1.2,
    menu: [
      "Dave's Single",
      "Spicy Chicken Sandwich",
      "Baconator",
      "Nuggets",
      "Frosty",
      "Fries",
      "Chili",
      "Baked Potato",
      "Garden Salad",
      "Homestyle Chicken Sandwich"
    ],
    ubereatsMenuPrice: [5.59, 6.09, 7.09, 4.59, 2.09, 2.29, 3.09, 3.59, 5.09, 5.69],
    doordashMenuPrice: [5.79, 5.99, 7.29, 4.49, 1.99, 2.39, 2.99, 3.49, 4.99, 5.59],
    grubhubMenuPrice: [5.69, 6.19, 7.19, 4.69, 1.89, 2.19, 2.89, 3.39, 4.89, 5.79],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/wendys/wendys-logo.png",
    menuItemImages: [
      "/images/wendys/daves_single.jpg",
      "/images/wendys/spicy_chicken_sandwich.jpg",
      "/images/wendys/baconator.jpg",
      "/images/wendys/nuggets.jpg",
      "/images/wendys/frosty.jpg",
      "/images/wendys/fries.jpg",
      "/images/wendys/chili.jpg",
      "/images/wendys/baked_potato.jpg",
      "/images/wendys/garden_salad.jpg",
      "/images/wendys/homestyle_chicken_sandwich.jpg"
    ]
  },
  {
    restaurantID: "i7j8k9l",
    restaurantName: "Wendy's",
    restaurantAddress: "789 Pine Road, 12347",
    distance: 2.0,
    menu: [
      "Dave's Single",
      "Spicy Chicken Sandwich",
      "Baconator",
      "Nuggets",
      "Frosty",
      "Fries",
      "Chili",
      "Baked Potato",
      "Garden Salad",
      "Homestyle Chicken Sandwich"
    ],
    ubereatsMenuPrice: [5.39, 5.89, 6.89, 4.39, 1.89, 2.09, 2.89, 3.39, 4.89, 5.49],
    doordashMenuPrice: [5.49, 5.79, 7.09, 4.29, 1.79, 2.19, 2.79, 3.29, 4.79, 5.39],
    grubhubMenuPrice: [5.29, 5.99, 6.99, 4.49, 1.69, 1.99, 2.69, 3.19, 4.69, 5.59],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/wendys/wendys-logo.png",
    menuItemImages: [
      "/images/wendys/daves_single.jpg",
      "/images/wendys/spicy_chicken_sandwich.jpg",
      "/images/wendys/baconator.jpg",
      "/images/wendys/nuggets.jpg",
      "/images/wendys/frosty.jpg",
      "/images/wendys/fries.jpg",
      "/images/wendys/chili.jpg",
      "/images/wendys/baked_potato.jpg",
      "/images/wendys/garden_salad.jpg",
      "/images/wendys/homestyle_chicken_sandwich.jpg"
    ]
  },
  {
    restaurantID: "m0n1o2p",
    restaurantName: "Wendy's",
    restaurantAddress: "321 Cedar Lane, 12348",
    distance: 2.8,
    menu: [
      "Dave's Single",
      "Spicy Chicken Sandwich",
      "Baconator",
      "Nuggets",
      "Frosty",
      "Fries",
      "Chili",
      "Baked Potato",
      "Garden Salad",
      "Homestyle Chicken Sandwich"
    ],
    ubereatsMenuPrice: [5.69, 6.19, 7.19, 4.69, 2.19, 2.39, 3.19, 3.69, 5.19, 5.79],
    doordashMenuPrice: [5.59, 6.09, 7.29, 4.59, 2.09, 2.49, 3.09, 3.59, 5.09, 5.69],
    grubhubMenuPrice: [5.79, 6.29, 7.09, 4.79, 1.99, 2.29, 2.99, 3.49, 4.99, 5.89],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/wendys/wendys-logo.png",
    menuItemImages: [
      "/images/wendys/daves_single.jpg",
      "/images/wendys/spicy_chicken_sandwich.jpg",
      "/images/wendys/baconator.jpg",
      "/images/wendys/nuggets.jpg",
      "/images/wendys/frosty.jpg",
      "/images/wendys/fries.jpg",
      "/images/wendys/chili.jpg",
      "/images/wendys/baked_potato.jpg",
      "/images/wendys/garden_salad.jpg",
      "/images/wendys/homestyle_chicken_sandwich.jpg"
    ]
  },
  {
    restaurantID: "q3r4s5t",
    restaurantName: "Popeyes",
    restaurantAddress: "987 Elm Street, 23456",
    distance: 0.9,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Tenders",
      "Popcorn Shrimp",
      "Cajun Fries",
      "Red Beans & Rice",
      "Biscuits",
      "Mashed Potatoes with Gravy",
      "Coleslaw",
      "Apple Pie"
    ],
    ubereatsMenuPrice: [3.99, 4.19, 5.49, 6.99, 2.49, 2.69, 0.99, 2.99, 1.89, 1.59],
    doordashMenuPrice: [4.09, 4.29, 5.59, 7.09, 2.39, 2.79, 1.09, 2.89, 1.79, 1.69],
    grubhubMenuPrice: [3.89, 4.39, 5.69, 6.89, 2.29, 2.59, 0.89, 2.79, 1.99, 1.49],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/popeyes/popeyes-logo.png",
    menuItemImages: [
      "/images/popeyes/chicken_sandwich.jpg",
      "/images/popeyes/spicy_chicken_sandwich.jpg",
      "/images/popeyes/chicken_tenders.jpg",
      "/images/popeyes/popcorn_shrimp.jpg",
      "/images/popeyes/cajun_fries.jpg",
      "/images/popeyes/red_beans_rice.jpg",
      "/images/popeyes/biscuits.jpg",
      "/images/popeyes/mashed_potatoes.jpg",
      "/images/popeyes/coleslaw.jpg",
      "/images/popeyes/apple_pie.jpg"
    ]
  },
  {
    restaurantID: "u6v7w8x",
    restaurantName: "Popeyes",
    restaurantAddress: "654 Spruce Avenue, 23457",
    distance: 1.5,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Tenders",
      "Popcorn Shrimp",
      "Cajun Fries",
      "Red Beans & Rice",
      "Biscuits",
      "Mashed Potatoes with Gravy",
      "Coleslaw",
      "Apple Pie"
    ],
    ubereatsMenuPrice: [4.09, 4.29, 5.69, 7.09, 2.59, 2.79, 1.09, 3.09, 1.99, 1.69],
    doordashMenuPrice: [3.99, 4.19, 5.49, 6.99, 2.49, 2.69, 0.99, 2.99, 1.89, 1.59],
    grubhubMenuPrice: [4.19, 4.39, 5.79, 7.19, 2.69, 2.89, 1.19, 3.19, 2.09, 1.79],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/popeyes/popeyes-logo.png",
    menuItemImages: [
      "/images/popeyes/chicken_sandwich.jpg",
      "/images/popeyes/spicy_chicken_sandwich.jpg",
      "/images/popeyes/chicken_tenders.jpg",
      "/images/popeyes/popcorn_shrimp.jpg",
      "/images/popeyes/cajun_fries.jpg",
      "/images/popeyes/red_beans_rice.jpg",
      "/images/popeyes/biscuits.jpg",
      "/images/popeyes/mashed_potatoes.jpg",
      "/images/popeyes/coleslaw.jpg",
      "/images/popeyes/apple_pie.jpg"
    ]
  },
  {
    restaurantID: "y9z0a1b",
    restaurantName: "Popeyes",
    restaurantAddress: "321 Birch Road, 23458",
    distance: 2.3,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Tenders",
      "Popcorn Shrimp",
      "Cajun Fries",
      "Red Beans & Rice",
      "Biscuits",
      "Mashed Potatoes with Gravy",
      "Coleslaw",
      "Apple Pie"
    ],
    ubereatsMenuPrice: [4.19, 4.39, 5.79, 7.19, 2.69, 2.89, 1.19, 3.19, 2.09, 1.79],
    doordashMenuPrice: [4.29, 4.49, 5.89, 7.29, 2.79, 2.99, 1.29, 3.29, 2.19, 1.89],
    grubhubMenuPrice: [4.09, 4.59, 5.99, 7.09, 2.59, 2.79, 1.09, 3.09, 1.99, 1.99],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/popeyes/popeyes-logo.png",
    menuItemImages: [
      "/images/popeyes/chicken_sandwich.jpg",
      "/images/popeyes/spicy_chicken_sandwich.jpg",
      "/images/popeyes/chicken_tenders.jpg",
      "/images/popeyes/popcorn_shrimp.jpg",
      "/images/popeyes/cajun_fries.jpg",
      "/images/popeyes/red_beans_rice.jpg",
      "/images/popeyes/biscuits.jpg",
      "/images/popeyes/mashed_potatoes.jpg",
      "/images/popeyes/coleslaw.jpg",
      "/images/popeyes/apple_pie.jpg"
    ]
  },
  {
    restaurantID: "c2d3e4f",
    restaurantName: "Popeyes",
    restaurantAddress: "852 Willow Lane, 23459",
    distance: 3.1,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Tenders",
      "Popcorn Shrimp",
      "Cajun Fries",
      "Red Beans & Rice",
      "Biscuits",
      "Mashed Potatoes with Gravy",
      "Coleslaw",
      "Apple Pie"
    ],
    ubereatsMenuPrice: [4.29, 4.49, 5.89, 7.29, 2.79, 2.99, 1.29, 3.29, 2.19, 1.89],
    doordashMenuPrice: [4.19, 4.39, 5.79, 7.19, 2.69, 2.89, 1.19, 3.19, 2.09, 1.79],
    grubhubMenuPrice: [4.39, 4.59, 5.99, 7.39, 2.89, 3.09, 1.39, 3.39, 2.29, 1.99],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/popeyes/popeyes-logo.png",
    menuItemImages: [
      "/images/popeyes/chicken_sandwich.jpg",
      "/images/popeyes/spicy_chicken_sandwich.jpg",
      "/images/popeyes/chicken_tenders.jpg",
      "/images/popeyes/popcorn_shrimp.jpg",
      "/images/popeyes/cajun_fries.jpg",
      "/images/popeyes/red_beans_rice.jpg",
      "/images/popeyes/biscuits.jpg",
      "/images/popeyes/mashed_potatoes.jpg",
      "/images/popeyes/coleslaw.jpg",
      "/images/popeyes/apple_pie.jpg"
    ]
  },
  {
    restaurantID: "g5h6i7j",
    restaurantName: "Pizza Hut",
    restaurantAddress: "159 Oak Street, 34567",
    distance: 0.6,
    menu: [
      "Pepperoni Pizza",
      "Cheese Pizza",
      "Supreme Pizza",
      "Meat Lover's Pizza",
      "Veggie Lover's Pizza",
      "Breadsticks",
      "Wings",
      "Pasta",
      "Salad",
      "Cinnamon Sticks"
    ],
    ubereatsMenuPrice: [12.99, 11.99, 14.99, 15.99, 13.99, 5.99, 8.99, 9.99, 4.99, 5.49],
    doordashMenuPrice: [13.49, 12.49, 15.49, 16.49, 14.49, 6.49, 9.49, 10.49, 5.49, 5.99],
    grubhubMenuPrice: [12.49, 11.49, 14.49, 15.49, 13.49, 5.49, 8.49, 9.49, 4.49, 4.99],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Italian",
    operatingHours: ["All Day"],
    restaurantImage: "/images/pizzahut/pizzahut-logo.png",
    menuItemImages: [
      "/images/pizzahut/pepperoni_pizza.jpg",
      "/images/pizzahut/cheese_pizza.jpg",
      "/images/pizzahut/supreme_pizza.jpg",
      "/images/pizzahut/meat_lovers_pizza.jpg",
      "/images/pizzahut/veggie_lovers_pizza.jpg",
      "/images/pizzahut/breadsticks.jpg",
      "/images/pizzahut/wings.jpg",
      "/images/pizzahut/pasta.jpg",
      "/images/pizzahut/salad.jpg",
      "/images/pizzahut/cinnamon_sticks.jpg"
    ]
  },
  {
    restaurantID: "k8l9m0n",
    restaurantName: "Pizza Hut",
    restaurantAddress: "753 Pine Avenue, 34568",
    distance: 1.4,
    menu: [
      "Pepperoni Pizza",
      "Cheese Pizza",
      "Supreme Pizza",
      "Meat Lover's Pizza",
      "Veggie Lover's Pizza",
      "Breadsticks",
      "Wings",
      "Pasta",
      "Salad",
      "Cinnamon Sticks"
    ],
    ubereatsMenuPrice: [13.09, 12.09, 15.09, 16.09, 14.09, 6.09, 9.09, 10.09, 5.09, 5.59],
    doordashMenuPrice: [12.99, 11.99, 14.99, 15.99, 13.99, 5.99, 8.99, 9.99, 4.99, 5.49],
    grubhubMenuPrice: [13.19, 12.19, 15.19, 16.19, 14.19, 6.19, 9.19, 10.19, 5.19, 5.69],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "Italian",
    operatingHours: ["All Day"],
    restaurantImage: "/images/pizzahut/pizzahut-logo.png",
    menuItemImages: [
      "/images/pizzahut/pepperoni_pizza.jpg",
      "/images/pizzahut/cheese_pizza.jpg",
      "/images/pizzahut/supreme_pizza.jpg",
      "/images/pizzahut/meat_lovers_pizza.jpg",
      "/images/pizzahut/veggie_lovers_pizza.jpg",
      "/images/pizzahut/breadsticks.jpg",
      "/images/pizzahut/wings.jpg",
      "/images/pizzahut/pasta.jpg",
      "/images/pizzahut/salad.jpg",
      "/images/pizzahut/cinnamon_sticks.jpg"
    ]
  },
  {
    restaurantID: "o1p2q3r",
    restaurantName: "Pizza Hut",
    restaurantAddress: "246 Birch Road, 34569",
    distance: 2.5,
    menu: [
      "Pepperoni Pizza",
      "Cheese Pizza",
      "Supreme Pizza",
      "Meat Lover's Pizza",
      "Veggie Lover's Pizza",
      "Breadsticks",
      "Wings",
      "Pasta",
      "Salad",
      "Cinnamon Sticks"
    ],
    ubereatsMenuPrice: [12.89, 11.89, 14.89, 15.89, 13.89, 5.89, 8.89, 9.89, 4.89, 5.39],
    doordashMenuPrice: [13.09, 12.09, 15.09, 16.09, 14.09, 6.09, 9.09, 10.09, 5.09, 5.59],
    grubhubMenuPrice: [12.79, 11.79, 14.79, 15.79, 13.79, 5.79, 8.79, 9.79, 4.79, 5.29],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "Italian",
    operatingHours: ["All Day"],
    restaurantImage: "/images/pizzahut/pizzahut-logo.png",
    menuItemImages: [
      "/images/pizzahut/pepperoni_pizza.jpg",
      "/images/pizzahut/cheese_pizza.jpg",
      "/images/pizzahut/supreme_pizza.jpg",
      "/images/pizzahut/meat_lovers_pizza.jpg",
      "/images/pizzahut/veggie_lovers_pizza.jpg",
      "/images/pizzahut/breadsticks.jpg",
      "/images/pizzahut/wings.jpg",
      "/images/pizzahut/pasta.jpg",
      "/images/pizzahut/salad.jpg",
      "/images/pizzahut/cinnamon_sticks.jpg"
    ]
  },
  {
    restaurantID: "s4t5u6v",
    restaurantName: "Pizza Hut",
    restaurantAddress: "987 Cedar Lane, 34570",
    distance: 3.2,
    menu: [
      "Pepperoni Pizza",
      "Cheese Pizza",
      "Supreme Pizza",
      "Meat Lover's Pizza",
      "Veggie Lover's Pizza",
      "Breadsticks",
      "Wings",
      "Pasta",
      "Salad",
      "Cinnamon Sticks"
    ],
    ubereatsMenuPrice: [13.19, 12.19, 15.19, 16.19, 14.19, 6.19, 9.19, 10.19, 5.19, 5.69],
    doordashMenuPrice: [13.29, 12.29, 15.29, 16.29, 14.29, 6.29, 9.29, 10.29, 5.29, 5.79],
    grubhubMenuPrice: [13.09, 12.09, 15.09, 16.09, 14.09, 6.09, 9.09, 10.09, 5.09, 5.59],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Italian",
    operatingHours: ["All Day"],
    restaurantImage: "/images/pizzahut/pizzahut-logo.png",
    menuItemImages: [
      "/images/pizzahut/pepperoni_pizza.jpg",
      "/images/pizzahut/cheese_pizza.jpg",
      "/images/pizzahut/supreme_pizza.jpg",
      "/images/pizzahut/meat_lovers_pizza.jpg",
      "/images/pizzahut/veggie_lovers_pizza.jpg",
      "/images/pizzahut/breadsticks.jpg",
      "/images/pizzahut/wings.jpg",
      "/images/pizzahut/pasta.jpg",
      "/images/pizzahut/salad.jpg",
      "/images/pizzahut/cinnamon_sticks.jpg"
    ]
  },
  {
    restaurantID: "d8e9f0g",
    restaurantName: "Subway",
    restaurantAddress: "123 Main Street, 45678",
    distance: 0.5,
    menu: [
      "Italian B.M.T.",
      "Turkey Breast",
      "Veggie Delite",
      "Chicken Teriyaki",
      "Meatball Marinara",
      "Tuna",
      "Black Forest Ham",
      "Steak & Cheese",
      "Roasted Chicken",
      "Subway Club"
    ],
    ubereatsMenuPrice: [5.99, 5.49, 4.99, 6.49, 5.99, 5.49, 5.29, 6.99, 6.49, 6.19],
    doordashMenuPrice: [6.19, 5.69, 5.19, 6.69, 6.19, 5.69, 5.49, 7.19, 6.69, 6.39],
    grubhubMenuPrice: [5.89, 5.39, 4.89, 6.29, 5.89, 5.39, 5.19, 6.89, 6.29, 6.09],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/subway/subway-logo.png",
    menuItemImages: [
      "/images/subway/italian_bmt.jpg",
      "/images/subway/turkey_breast.jpg",
      "/images/subway/veggie_delite.jpg",
      "/images/subway/chicken_teriyaki.jpg",
      "/images/subway/meatball_marinara.jpg",
      "/images/subway/tuna.jpg",
      "/images/subway/black_forest_ham.jpg",
      "/images/subway/steak_cheese.jpg",
      "/images/subway/roasted_chicken.jpg",
      "/images/subway/subway_club.jpg"
    ]
  },
  {
    restaurantID: "h1i2j3k",
    restaurantName: "Subway",
    restaurantAddress: "456 Elm Avenue, 45679",
    distance: 1.1,
    menu: [
      "Italian B.M.T.",
      "Turkey Breast",
      "Veggie Delite",
      "Chicken Teriyaki",
      "Meatball Marinara",
      "Tuna",
      "Black Forest Ham",
      "Steak & Cheese",
      "Roasted Chicken",
      "Subway Club"
    ],
    ubereatsMenuPrice: [6.09, 5.59, 5.09, 6.59, 6.09, 5.59, 5.39, 7.09, 6.59, 6.29],
    doordashMenuPrice: [5.99, 5.49, 4.99, 6.49, 5.99, 5.49, 5.29, 6.99, 6.49, 6.19],
    grubhubMenuPrice: [6.19, 5.69, 5.19, 6.69, 6.19, 5.69, 5.49, 7.19, 6.69, 6.39],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/subway/subway-logo.png",
    menuItemImages: [
      "/images/subway/italian_bmt.jpg",
      "/images/subway/turkey_breast.jpg",
      "/images/subway/veggie_delite.jpg",
      "/images/subway/chicken_teriyaki.jpg",
      "/images/subway/meatball_marinara.jpg",
      "/images/subway/tuna.jpg",
      "/images/subway/black_forest_ham.jpg",
      "/images/subway/steak_cheese.jpg",
      "/images/subway/roasted_chicken.jpg",
      "/images/subway/subway_club.jpg"
    ]
  },
  {
    restaurantID: "l4m5n6o",
    restaurantName: "Subway",
    restaurantAddress: "789 Pine Road, 45680",
    distance: 2.0,
    menu: [
      "Italian B.M.T.",
      "Turkey Breast",
      "Veggie Delite",
      "Chicken Teriyaki",
      "Meatball Marinara",
      "Tuna",
      "Black Forest Ham",
      "Steak & Cheese",
      "Roasted Chicken",
      "Subway Club"
    ],
    ubereatsMenuPrice: [5.89, 5.39, 4.89, 6.29, 5.89, 5.39, 5.19, 6.89, 6.29, 6.09],
    doordashMenuPrice: [6.09, 5.59, 5.09, 6.59, 6.09, 5.59, 5.39, 7.09, 6.59, 6.29],
    grubhubMenuPrice: [5.79, 5.29, 4.79, 6.19, 5.79, 5.29, 5.09, 6.79, 6.19, 5.99],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/subway/subway-logo.png",
    menuItemImages: [
      "/images/subway/italian_bmt.jpg",
      "/images/subway/turkey_breast.jpg",
      "/images/subway/veggie_delite.jpg",
      "/images/subway/chicken_teriyaki.jpg",
      "/images/subway/meatball_marinara.jpg",
      "/images/subway/tuna.jpg",
      "/images/subway/black_forest_ham.jpg",
      "/images/subway/steak_cheese.jpg",
      "/images/subway/roasted_chicken.jpg",
      "/images/subway/subway_club.jpg"
    ]
  },
  {
    restaurantID: "p7q8r9s",
    restaurantName: "Subway",
    restaurantAddress: "321 Cedar Lane, 45681",
    distance: 2.7,
    menu: [
      "Italian B.M.T.",
      "Turkey Breast",
      "Veggie Delite",
      "Chicken Teriyaki",
      "Meatball Marinara",
      "Tuna",
      "Black Forest Ham",
      "Steak & Cheese",
      "Roasted Chicken",
      "Subway Club"
    ],
    ubereatsMenuPrice: [6.19, 5.69, 5.19, 6.69, 6.19, 5.69, 5.49, 7.19, 6.69, 6.39],
    doordashMenuPrice: [6.29, 5.79, 5.29, 6.79, 6.29, 5.79, 5.59, 7.29, 6.79, 6.49],
    grubhubMenuPrice: [6.09, 5.59, 5.09, 6.59, 6.09, 5.59, 5.39, 7.09, 6.59, 6.29],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["All Day"],
    restaurantImage: "/images/subway/subway-logo.png",
    menuItemImages: [
      "/images/subway/italian_bmt.jpg",
      "/images/subway/turkey_breast.jpg",
      "/images/subway/veggie_delite.jpg",
      "/images/subway/chicken_teriyaki.jpg",
      "/images/subway/meatball_marinara.jpg",
      "/images/subway/tuna.jpg",
      "/images/subway/black_forest_ham.jpg",
      "/images/subway/steak_cheese.jpg",
      "/images/subway/roasted_chicken.jpg",
      "/images/subway/subway_club.jpg"
    ]
  },
  {
    restaurantID: "t0u1v2w",
    restaurantName: "Taco Bell",
    restaurantAddress: "123 Maple Street, 56789",
    distance: 0.8,
    menu: [
      "Crunchy Taco",
      "Soft Taco",
      "Burrito Supreme",
      "Nachos BellGrande",
      "Crunchwrap Supreme",
      "Quesadilla",
      "Bean Burrito",
      "Mexican Pizza",
      "Cheesy Gordita Crunch",
      "Chalupa Supreme"
    ],
    ubereatsMenuPrice: [1.29, 1.39, 3.49, 3.99, 3.69, 3.29, 1.99, 4.49, 3.59, 3.29],
    doordashMenuPrice: [1.19, 1.29, 3.39, 3.89, 3.59, 3.19, 1.89, 4.39, 3.49, 3.19],
    grubhubMenuPrice: [1.39, 1.49, 3.59, 4.09, 3.79, 3.39, 2.09, 4.59, 3.69, 3.39],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["All Day"],
    restaurantImage: "/images/tacobell/tacobell-logo.png",
    menuItemImages: [
      "/images/tacobell/crunchy_taco.jpg",
      "/images/tacobell/soft_taco.jpg",
      "/images/tacobell/burrito_supreme.jpg",
      "/images/tacobell/nachos_bellgrande.jpg",
      "/images/tacobell/crunchwrap_supreme.jpg",
      "/images/tacobell/quesadilla.jpg",
      "/images/tacobell/bean_burrito.jpg",
      "/images/tacobell/mexican_pizza.jpg",
      "/images/tacobell/cheesy_gordita_crunch.jpg",
      "/images/tacobell/chalupa_supreme.jpg"
    ]
  },
  {
    restaurantID: "x3y4z5a",
    restaurantName: "Taco Bell",
    restaurantAddress: "456 Oak Avenue, 56790",
    distance: 1.3,
    menu: [
      "Crunchy Taco",
      "Soft Taco",
      "Burrito Supreme",
      "Nachos BellGrande",
      "Crunchwrap Supreme",
      "Quesadilla",
      "Bean Burrito",
      "Mexican Pizza",
      "Cheesy Gordita Crunch",
      "Chalupa Supreme"
    ],
    ubereatsMenuPrice: [1.39, 1.49, 3.59, 4.09, 3.79, 3.39, 2.09, 4.59, 3.69, 3.39],
    doordashMenuPrice: [1.29, 1.39, 3.49, 3.99, 3.69, 3.29, 1.99, 4.49, 3.59, 3.29],
    grubhubMenuPrice: [1.49, 1.59, 3.69, 4.19, 3.89, 3.49, 2.19, 4.69, 3.79, 3.49],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["All Day"],
    restaurantImage: "/images/tacobell/tacobell-logo.png",
    menuItemImages: [
      "/images/tacobell/crunchy_taco.jpg",
      "/images/tacobell/soft_taco.jpg",
      "/images/tacobell/burrito_supreme.jpg",
      "/images/tacobell/nachos_bellgrande.jpg",
      "/images/tacobell/crunchwrap_supreme.jpg",
      "/images/tacobell/quesadilla.jpg",
      "/images/tacobell/bean_burrito.jpg",
      "/images/tacobell/mexican_pizza.jpg",
      "/images/tacobell/cheesy_gordita_crunch.jpg",
      "/images/tacobell/chalupa_supreme.jpg"
    ]
  },
  {
    restaurantID: "b6c7d8e",
    restaurantName: "Taco Bell",
    restaurantAddress: "789 Pine Road, 56791",
    distance: 2.1,
    menu: [
      "Crunchy Taco",
      "Soft Taco",
      "Burrito Supreme",
      "Nachos BellGrande",
      "Crunchwrap Supreme",
      "Quesadilla",
      "Bean Burrito",
      "Mexican Pizza",
      "Cheesy Gordita Crunch",
      "Chalupa Supreme"
    ],
    ubereatsMenuPrice: [1.19, 1.29, 3.39, 3.89, 3.59, 3.19, 1.89, 4.39, 3.49, 3.19],
    doordashMenuPrice: [1.39, 1.49, 3.59, 4.09, 3.79, 3.39, 2.09, 4.59, 3.69, 3.39],
    grubhubMenuPrice: [1.29, 1.39, 3.49, 3.99, 3.69, 3.29, 1.99, 4.49, 3.59, 3.29],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "Mexican",
    operatingHours: ["All Day"],
    restaurantImage: "/images/tacobell/tacobell-logo.png",
    menuItemImages: [
      "/images/tacobell/crunchy_taco.jpg",
      "/images/tacobell/soft_taco.jpg",
      "/images/tacobell/burrito_supreme.jpg",
      "/images/tacobell/nachos_bellgrande.jpg",
      "/images/tacobell/crunchwrap_supreme.jpg",
      "/images/tacobell/quesadilla.jpg",
      "/images/tacobell/bean_burrito.jpg",
      "/images/tacobell/mexican_pizza.jpg",
      "/images/tacobell/cheesy_gordita_crunch.jpg",
      "/images/tacobell/chalupa_supreme.jpg"
    ]
  },
  {
    restaurantID: "e9f0g1h",
    restaurantName: "Taco Bell",
    restaurantAddress: "321 Cedar Lane, 56792",
    distance: 2.9,
    menu: [
      "Crunchy Taco",
      "Soft Taco",
      "Burrito Supreme",
      "Nachos BellGrande",
      "Crunchwrap Supreme",
      "Quesadilla",
      "Bean Burrito",
      "Mexican Pizza",
      "Cheesy Gordita Crunch",
      "Chalupa Supreme"
    ],
    ubereatsMenuPrice: [1.49, 1.59, 3.69, 4.19, 3.89, 3.49, 2.19, 4.69, 3.79, 3.49],
    doordashMenuPrice: [1.39, 1.49, 3.59, 4.09, 3.79, 3.39, 2.09, 4.59, 3.69, 3.39],
    grubhubMenuPrice: [1.59, 1.69, 3.79, 4.29, 3.99, 3.59, 2.29, 4.79, 3.89, 3.59],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "Mexican",
    operatingHours: ["All Day"],
    restaurantImage: "/images/tacobell/tacobell-logo.png",
    menuItemImages: [
      "/images/tacobell/crunchy_taco.jpg",
      "/images/tacobell/soft_taco.jpg",
      "/images/tacobell/burrito_supreme.jpg",
      "/images/tacobell/nachos_bellgrande.jpg",
      "/images/tacobell/crunchwrap_supreme.jpg",
      "/images/tacobell/quesadilla.jpg",
      "/images/tacobell/bean_burrito.jpg",
      "/images/tacobell/mexican_pizza.jpg",
      "/images/tacobell/cheesy_gordita_crunch.jpg",
      "/images/tacobell/chalupa_supreme.jpg"
    ]
  },
  {
    restaurantID: "i2j3k4l",
    restaurantName: "Chick-Fil-A",
    restaurantAddress: "159 Oak Street, 67890",
    distance: 0.7,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Nuggets",
      "Waffle Fries",
      "Grilled Chicken Sandwich",
      "Chicken Biscuit",
      "Lemonade",
      "Mac & Cheese",
      "Chicken Strips",
      "Chocolate Milkshake"
    ],
    ubereatsMenuPrice: [3.75, 3.99, 4.49, 1.99, 4.29, 2.89, 1.89, 2.99, 4.59, 3.29],
    doordashMenuPrice: [3.85, 4.09, 4.59, 2.09, 4.39, 2.99, 1.99, 3.09, 4.69, 3.39],
    grubhubMenuPrice: [3.65, 3.89, 4.39, 1.89, 4.19, 2.79, 1.79, 2.89, 4.49, 3.19],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chickfila/chickfila-logo.png",
    menuItemImages: [
      "/images/chickfila/chicken_sandwich.jpg",
      "/images/chickfila/spicy_chicken_sandwich.jpg",
      "/images/chickfila/nuggets.jpg",
      "/images/chickfila/waffle_fries.jpg",
      "/images/chickfila/grilled_chicken_sandwich.jpg",
      "/images/chickfila/chicken_biscuit.jpg",
      "/images/chickfila/lemonade.jpg",
      "/images/chickfila/mac_cheese.jpg",
      "/images/chickfila/chicken_strips.jpg",
      "/images/chickfila/chocolate_milkshake.jpg"
    ]
  },
  {
    restaurantID: "m5n6o7p",
    restaurantName: "Chick-Fil-A",
    restaurantAddress: "753 Pine Avenue, 67891",
    distance: 1.5,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Nuggets",
      "Waffle Fries",
      "Grilled Chicken Sandwich",
      "Chicken Biscuit",
      "Lemonade",
      "Mac & Cheese",
      "Chicken Strips",
      "Chocolate Milkshake"
    ],
    ubereatsMenuPrice: [3.85, 4.09, 4.59, 2.09, 4.39, 2.99, 1.99, 3.09, 4.69, 3.39],
    doordashMenuPrice: [3.75, 3.99, 4.49, 1.99, 4.29, 2.89, 1.89, 2.99, 4.59, 3.29],
    grubhubMenuPrice: [3.95, 4.19, 4.69, 2.19, 4.49, 3.09, 2.09, 3.19, 4.79, 3.49],
    ubereatsAvailable: false,
    doordashAvailable: true,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chickfila/chickfila-logo.png",
    menuItemImages: [
      "/images/chickfila/chicken_sandwich.jpg",
      "/images/chickfila/spicy_chicken_sandwich.jpg",
      "/images/chickfila/nuggets.jpg",
      "/images/chickfila/waffle_fries.jpg",
      "/images/chickfila/grilled_chicken_sandwich.jpg",
      "/images/chickfila/chicken_biscuit.jpg",
      "/images/chickfila/lemonade.jpg",
      "/images/chickfila/mac_cheese.jpg",
      "/images/chickfila/chicken_strips.jpg",
      "/images/chickfila/chocolate_milkshake.jpg"
    ]
  },
  {
    restaurantID: "q8r9s0t",
    restaurantName: "Chick-Fil-A",
    restaurantAddress: "246 Birch Road, 67892",
    distance: 2.4,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Nuggets",
      "Waffle Fries",
      "Grilled Chicken Sandwich",
      "Chicken Biscuit",
      "Lemonade",
      "Mac & Cheese",
      "Chicken Strips",
      "Chocolate Milkshake"
    ],
    ubereatsMenuPrice: [3.65, 3.89, 4.39, 1.89, 4.19, 2.79, 1.79, 2.89, 4.49, 3.19],
    doordashMenuPrice: [3.85, 4.09, 4.59, 2.09, 4.39, 2.99, 1.99, 3.09, 4.69, 3.39],
    grubhubMenuPrice: [3.75, 3.99, 4.49, 1.99, 4.29, 2.89, 1.89, 2.99, 4.59, 3.29],
    ubereatsAvailable: true,
    doordashAvailable: false,
    grubhubAvailable: true,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chickfila/chickfila-logo.png",
    menuItemImages: [
      "/images/chickfila/chicken_sandwich.jpg",
      "/images/chickfila/spicy_chicken_sandwich.jpg",
      "/images/chickfila/nuggets.jpg",
      "/images/chickfila/waffle_fries.jpg",
      "/images/chickfila/grilled_chicken_sandwich.jpg",
      "/images/chickfila/chicken_biscuit.jpg",
      "/images/chickfila/lemonade.jpg",
      "/images/chickfila/mac_cheese.jpg",
      "/images/chickfila/chicken_strips.jpg",
      "/images/chickfila/chocolate_milkshake.jpg"
    ]
  },
  {
    restaurantID: "u1v2w3x",
    restaurantName: "Chick-Fil-A",
    restaurantAddress: "987 Cedar Lane, 67893",
    distance: 3.3,
    menu: [
      "Chicken Sandwich",
      "Spicy Chicken Sandwich",
      "Chicken Nuggets",
      "Waffle Fries",
      "Grilled Chicken Sandwich",
      "Chicken Biscuit",
      "Lemonade",
      "Mac & Cheese",
      "Chicken Strips",
      "Chocolate Milkshake"
    ],
    ubereatsMenuPrice: [3.95, 4.19, 4.69, 2.19, 4.49, 3.09, 2.09, 3.19, 4.79, 3.49],
    doordashMenuPrice: [3.75, 3.99, 4.49, 1.99, 4.29, 2.89, 1.89, 2.99, 4.59, 3.29],
    grubhubMenuPrice: [4.05, 4.29, 4.79, 2.29, 4.59, 3.19, 2.19, 3.29, 4.89, 3.59],
    ubereatsAvailable: true,
    doordashAvailable: true,
    grubhubAvailable: false,
    cuisineType: "American",
    operatingHours: ["Breakfast", "Lunch", "Dinner"],
    restaurantImage: "/images/chickfila/chickfila-logo.png",
    menuItemImages: [
      "/images/chickfila/chicken_sandwich.jpg",
      "/images/chickfila/spicy_chicken_sandwich.jpg",
      "/images/chickfila/nuggets.jpg",
      "/images/chickfila/waffle_fries.jpg",
      "/images/chickfila/grilled_chicken_sandwich.jpg",
      "/images/chickfila/chicken_biscuit.jpg",
      "/images/chickfila/lemonade.jpg",
      "/images/chickfila/mac_cheese.jpg",
      "/images/chickfila/chicken_strips.jpg",
      "/images/chickfila/chocolate_milkshake.jpg"
    ]
  }
  
];

export default restaurantData;
